name: 'Terraform'

on:
  workflow_dispatch:

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      RESOURCE_GROUP: ${{ secrets.RESOURCE_GROUP }}
      STORAGE_ACCOUNT: ${{ secrets.STORAGE_ACCOUNT }}
      CONTAINER_NAME: ${{ secrets.CONTAINER_NAME }}
    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v4.1.1
      
      # Install the preferred version of Terraform CLI
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.3
        with:
          terraform_version: 1.6.6
      
      # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
      - name: Terraform Init
        id: init
        run: terraform init -backend-config="storage_account_name=$STORAGE_ACCOUNT" -backend-config="container_name=$CONTAINER_NAME" -backend-config="resource_group_name=$RESOURCE_GROUP"
      
      # Run a terraform plan and save the output to a file
      - name: Terraform Plan
        id: plan
        run: terraform plan -out=tfplan -no-color
      
      # Upload the plan file as an artifact (optional, for debugging or later use)
      - name: Upload Terraform Plan
        uses: actions/upload-artifact@v3.1.2
        with:
          name: terraform-plan
          path: tfplan

  manual_approval:
    name: 'Manual Approval'
    needs: terraform
    runs-on: ubuntu-latest
    steps:
      - name: Await Manual Approval
        run: echo "Please review the Terraform plan and approve the workflow to proceed."

  terraform_apply:
    name: 'Terraform Apply'
    needs: manual_approval
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository again to ensure the plan file is available
      - name: Checkout
        uses: actions/checkout@v4.1.1

      # Install Terraform again for the apply step
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.3
        with:
          terraform_version: 1.6.6

      # Apply the saved plan
      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan